name: Create Release

on: 
  push:
    tags:
    - 'v[0-9].[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: "misc/LATEST_RELEASE_BODY"
        makeLatest: makeLatest
